<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZajitTT\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZajitTT/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerZajitTT.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerZajitTT\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerZajitTT\App_KernelTestDebugContainer([
    'container.build_hash' => 'ZajitTT',
    'container.build_id' => '554197cf',
    'container.build_time' => 1715691436,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZajitTT');
