<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPxk5ktq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxk5ktq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPxk5ktq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPxk5ktq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPxk5ktq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pxk5ktq',
    'container.build_id' => 'f004ab86',
    'container.build_time' => 1715692380,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPxk5ktq');
