<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'main' => [['date', 'city'], ['_controller' => 'App\\Controller\\MainController::index'], [], [['variable', '-', '[^/]++', 'city', true], ['variable', '', '[^/\\-]++', 'date', true], ['text', '/main']], [], [], []],
    'app_recommendation_create' => [[], ['_controller' => 'App\\Controller\\RecommendationController::create'], [], [['text', '/api/recommendations']], [], [], []],
    'App\Controller\MainController::index' => [['date', 'city'], ['_controller' => 'App\\Controller\\MainController::index'], [], [['variable', '-', '[^/]++', 'city', true], ['variable', '', '[^/\\-]++', 'date', true], ['text', '/main']], [], [], []],
    'App\Controller\RecommendationController::create' => [[], ['_controller' => 'App\\Controller\\RecommendationController::create'], [], [['text', '/api/recommendations']], [], [], []],
];
